version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app-20220114a"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-nj7ajoeelvj9"
s3_prefix = "sam-app-20220114a"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
